apiVersion: v1
kind: Service
metadata:
  name: ecommerce-api
  labels:
    app: ecommerce-api
spec:
  type: {{ .Values.ecommerceApi.service.type }}
  ports:
    - port: {{ .Values.ecommerceApi.service.port }}
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    app: ecommerce-api 