apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  replicas: {{ .Values.userApi.replicaCount }}
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: {{ .Values.userApi.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            {{- range $key, $value := .Values.userApi.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }} 