apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: tic-2025-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: tic-2025-frontend
  template:
    metadata:
      labels:
        app: tic-2025-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: 3000
          env:
            {{- range $key, $value := .Values.frontend.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }} 