apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: tic-2025-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-2025-redis
  template:
    metadata:
      labels:
        app: tic-2025-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc 