apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: tic-2025-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: tic-2025-backend
  template:
    metadata:
      labels:
        app: tic-2025-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret 