apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: tic-2025-frontend
data:
  REACT_APP_API_URL: "{{ .Values.frontend.env.REACT_APP_API_URL | default "http://backend:8000" }}" 