{{- if .Values.backend.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tic-2025.fullname" . }}-backend-api-docs-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tic-2025.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.backend.persistence.apiDocs.storageClass }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.apiDocs.size }}
{{- end }} 