apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tic-2025.fullname" . }}-backend-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tic-2025.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend

data:
  ACCESS_TOKEN_EXPIRE_MINUTES: "{{ .Values.backend.env.ACCESS_TOKEN_EXPIRE_MINUTES | default "30" }}"
  API_DOCS_DIR: "{{ .Values.backend.env.API_DOCS_DIR | default "api-docs" }}"
  LOGS_DIR: "{{ .Values.backend.env.LOGS_DIR | default "logs" }}"
  MAX_CONCURRENT_TESTS: "{{ .Values.backend.env.MAX_CONCURRENT_TESTS | default "10" }}"
  TEST_TIMEOUT: "{{ .Values.backend.env.TEST_TIMEOUT | default "30" }}" 
  CORS_ALLOW_ORIGINS: "{{ .Values.backend.env.CORS_ALLOW_ORIGINS | default "*" }}"