apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tic-2025.fullname" . }}-backend-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tic-2025.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  DATABASE_URL: {{ .Values.backend.env.DATABASE_URL | b64enc | quote }}
  REDIS_URL: {{ .Values.backend.env.REDIS_URL | b64enc | quote }}
  SECRET_KEY: {{ .Values.backend.env.SECRET_KEY | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.backend.env.OPENAI_API_KEY | b64enc | quote }}
  DEEPSEEK_API_KEY: {{ .Values.backend.env.DEEPSEEK_API_KEY | b64enc | quote }} 
  GEMINI_API_KEY: {{ .Values.backend.env.GEMINI_API_KEY | b64enc | quote }} 