apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tic-2025.fullname" . }}-frontend-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tic-2025.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  REACT_APP_API_URL: "{{ .Values.frontend.env.REACT_APP_API_URL | default "https://apitestgen-api.lab.tekodata.com" }}" 