apiVersion: v1
kind: Service
metadata:
  name: {{ include "tic-2025.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tic-2025.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "tic-2025.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend 